baseURL: "https://skarlso.github.io"
languageCode: "en"
defaultContentLanguage: "en"
title: "Ramblings of a cloud engineer"
theme: "PaperMod"
disqusShortname: "hannibalDisqus"
paginate: 10

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 15
        - name: Categories
          url: categories/
          weight: 20

editPost:
  URL: "https://github.com/Skarlso/skarlso.github.io"
  Text: "Suggest Changes" # edit text
  appendFilePath: true # to append file path to Edit link

params:
  author: "Gergely Brautigam"
  disableSpecial1stPost: true
  comments: true
  env: "production"
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04 -0700"
  listDateFormat: "1. January"
  listDatePosition: "right"
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  description: "Welcome to my little corner of the internet"
  footerCopyright: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)'
  fofPoster: ""

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent: false  # Set "text-align: justify" to `.content`.
  archivePaginate: 50
  # version: "4.x"
  homeInfoParams:
    Title: "Ramblings of a cloud engineer"
    Content: >
      Welcome to my little corner of the internet.
  socialIcons:
    - name: github
      url: "https://github.com/Skarlso"
    - name: Rss
      url: "index.xml"
    - name: twitter
      url: "https://twitter.com/skarlso"

  menu:
    main:
      - name: "Archive"
        url: "/posts/"
        weight: 10
      - name: "Tags"
        url: "/tags/"
        weight: 30
      - name: "Categories"
        url: "/categories/"
        weight: 40

markup:
  tableOfContents:
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
